# Generated by Django 3.0.4 on 2020-04-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200407_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_details',
            old_name='account_no',
            new_name='User_account_no',
        ),
    ]
