# Generated by Django 3.0.4 on 2020-04-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200403_1403'),
        ('account', '0002_account_details'),
    ]

    operations = [
    ]
