# Generated by Django 3.0.5 on 2020-04-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useractivation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useractivation',
            table='user_activation',
        ),
    ]
