# Generated by Django 3.0.5 on 2020-04-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_details',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
