# Generated by Django 3.0.5 on 2020-04-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_details_balance'),
        ('account', '0002_auto_20200403_1403'),
    ]

    operations = [
    ]
