# Generated by Django 3.0.5 on 2020-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200409_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='IFSC',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='Recipient_Name',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='account_no',
        ),
        migrations.AddField(
            model_name='account_details',
            name='current_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='current_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=110),
        ),
    ]
