# Generated by Django 3.0.5 on 2020-04-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_merge_20200403_1713'),
        ('account', '0005_merge_20200403_1709'),
    ]

    operations = [
    ]
