# Generated by Django 3.0.5 on 2020-04-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200409_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='account_type',
            field=models.CharField(choices=[('Current', 'Current'), ('Saving', 'Saving'), ('Capital', 'Capital')], max_length=20),
        ),
    ]
