# Generated by Django 3.0.5 on 2020-04-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200410_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
