# Generated by Django 3.0.5 on 2020-04-11 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=110)),
                ('amount', models.FloatField()),
                ('current_user', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('balance', models.FloatField()),
                ('recipient_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account_details')),
            ],
            options={
                'verbose_name_plural': 'TRANSACTIONs',
                'db_table': 'transactions',
                'managed': True,
            },
        ),
    ]
